apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-spring-app-auth-ingress
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-spring-app-auth-service
                port:
                  number: 8080
