apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spring-auth-app-service
  labels:
    app: {{ .Release.Name }}-spring-auth-app
spec:
  selector:
    app: {{ .Release.Name }}-spring-auth-app
  ports:
      - protocol: TCP
        name: metrics
        port: 8081
        targetPort: 8081
  type: LoadBalancer